### PR TITLE
Added dark theme and a couple of other accent options + Fixed dead links in Glossary

### PR DESCRIPTION
**Pull request by YT-GameWorks**
If you now click on the settings icon on the top bar few options appear, including dark theme! and some accent options (note: hasn't been tested on every page.. could be broken). this is very similar to the way that the discord js guide also adds themes

### CODE REVIEW

**Comment by YT-GameWorks** [comment]
dark theme preview

Here's a little preview of it in action!

**Comment by Aktindo** [comment]
Ah nice :) this will help developers read the documentation much better. _(without burning their eyes XD)_

**Comment by Bastian** [comment]
Awesome, thx!

**Comment by YT-GameWorks** [comment]
> Awesome, thx!

Np! This is the first time my PR got merged in any repo :D

**Pull request merged**
